CREATE TABLE IF NOT EXISTS app_users (
    id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar NOT NULL,
    login varchar NOT NULL,
    name varchar NOT NULL,
    birthday date
);

CREATE TABLE IF NOT EXISTS friends (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id INT8 REFERENCES app_users (id),
    recipient_id INT8 REFERENCES app_users (id)
);

CREATE TABLE IF NOT EXISTS rating_mpa (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
    id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL,
    description varchar(200),
    release_date date,
    duration INTEGER,
    rating_mpa_id INTEGER REFERENCES rating_mpa (id)
);

CREATE TABLE IF NOT EXISTS likes (
    film_id INT8 REFERENCES films (id),
    user_id INT8 REFERENCES app_users (id),
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS genre (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id INT8 REFERENCES films (id),
    name varchar
);